name: Contact Manager CI/CD workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Resolve image tag
        run: |
          echo "image_tag=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "Image tag: ${{ env.image_tag }}"
      - name: Build image
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=contact-manager-api:${{ env.image_tag }}
